site_name: "" 
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  custom_dir: overrides
extra_css:
  - stylesheets/style.css
nav:
  - Edge Delta Overview: index.md
  - Basic Onboarding: basic-onboarding.md
  - Architecture Overview - K8s: architecture-overview-k8s.md
  - Installation:
    - Overview: installation/index.md
    - Environment Variables: installation/environment-variables.md
    - Windows: installation/windows.md
    - Linux: installation/linux.md
    - Docker: installation/docker.md
    - MacOS: installation/macos.md
    - Kubernetes: installation/kubernetes.md
    - Kubernetes via Helm: installation/helm.md
    - Amazon ECS: installation/amazon-ecs.md
    - Agent Network Access Requirements: installation/network-access.md
  - Configuration:
    - Overview: configuration/index.md
    - Cloud Configuration Backend: configuration/ccb.md
    - Agent Settings: configuration/agent-settings.md
    - Inputs: configuration/inputs.md
    - Filters: configuration/filters.md
    - Thresholds: configuration/thresholds.md
    - Outputs: configuration/outputs.md
    - Processors: configuration/processors.md
    - Workflows: configuration/workflows.md
    - Variables: configuration/variables.md
  - Examples:
    - Overview: examples/index.md
    - Linux Configuration: examples/linux-configuration.md
    - Windows Configuration: examples/windows-configuration.md
    - Kubernetes Configuration: examples/kubernetes-example.md
    - Docker Configuration: examples/docker-configuration.md
  - Appendices:
    - Overview: appendices/index.md
    - Elastic Index Setup: appendices/elastic-index.md
    - Azure Function Monitoring Setup: appendices/azure-serverless-monitoring.md
    - Clustering Details: appendices/clustering.md
    - MultiLine Detection: appendices/line_detection.md
    - Ingestion to ED Backend Preferences: appendices/data_preferences.md
    - Benchmark Test Results: appendices/benchmark_results.md
    - Custom Metric Alerts: appendices/custom-metric-alerts.md
    - Monitors: appendices/monitors.md
    - Prometheus Scraping: appendices/prometheus-scraping.md
    - Trigger Payload Template Values: appendices/template-values.md
    - Role Based Access Control: appendices/rbac.md
