version: 2.1

orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build_and_publish_page:
    docker:
      - image: honkit/honkit
    working_directory: /docs
    steps:
      - checkout
      - run:
          name: Build and Publish
          command: |
            npm install
            npm install -g gitbook-plugin-hints
            honkit init
            honkit build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=3600" \
            --delete
          aws-access-key-id: DOCS_PUBLISHER_KEY_ID
          aws-secret-access-key: DOCS_PUBLISHER_KEY
          aws-region: DEFAULT_AWS_REGION
          from: /docs/_book
          to: s3://$DOCS_BUCKET_NAME

workflows:
  main:
    jobs:
      - build_and_publish_page:
          context: docs